### ISSUE TITLE
Improve AUP model documentation

### ISSUE THREAD

**Issue by NicolasLiampotis** [rciam/simplesamlphp-module-attrauthcomanage#50]
The AUP model documentation (`docs/model/aup.md`) needs to be improved as follows:

1. Add a definition for the `agreed` property, e.g. "Information on the last agreement for this AUP`. 
2. What's the value of the `agreed` property if the user hasn't agreed with the AUP? E.g. "Only defined if the user has agreed with a version of this AUP" or "Set to `null` if the user hasn't agreed with any version of this AUP"
3. What's the difference between `agreed.id` and `agreed.aup_id`? 
4. What's the value of the `vo` property if the AUP is not VO-specific? 

/cc @lionick

**Comment by ioigoume** [comment]
Related [Pull Request](https://github.com/rciam/simplesamlphp-module-attrauthcomanage/pull/51)

**Comment by NicolasLiampotis** [comment]
Closed with #51
